//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AItem()
        {
            this.AOrders = new HashSet<AOrder>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_item { get; set; }
        public string itname { get; set; }
        public Nullable<int> cat_id { get; set; }
        public Nullable<int> qty { get; set; }
        public Nullable<double> sold_qty { get; set; }
        public Nullable<double> cost { get; set; }
        public string manufacturer { get; set; }
        public string address { get; set; }
        public string telephone { get; set; }
        public Nullable<double> sales_price { get; set; }
        public Nullable<int> user_id { get; set; }
    
        public virtual ACategory ACategory { get; set; }
        public virtual Anshuja Anshuja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AOrder> AOrders { get; set; }
    }
}
